# Default values for llama-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
rawDeploymentMode: true

image:
  repository: llamastack/distribution-remote-vllm
  pullPolicy: IfNotPresent
  tag: "0.2.8"

imagePullSecrets: []
nameOverride: "llamastack"
fullnameOverride: "llamastack"

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

progressDeadlineSeconds: 3600

strategy:
  type: Recreate

service:
  type: ClusterIP
  port: 8321

args:
  - --config
  - /app-config/config.yaml
env:
  - name: VLLM_MAX_TOKENS
    value: "4096"
  - name: VLLM_API_TOKEN
    value: fake
  - name: OTEL_ENDPOINT
    value: http://otel-collector-collector.observability-hub.svc.cluster.local:4318/v1/traces
   
resources: {}

autoscaling:
  enabled: false

# Additional volumes on the output Deployment definition.
volumes:
  - configMap:
      defaultMode: 420
      name: run-config
    name: run-config-volume
  - name: dot-llama
    persistentVolumeClaim:
      claimName: llama-stack-data
  - emptyDir: {}
    name: cache

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - mountPath: /app-config
    name: run-config-volume
  - mountPath: /.llama
    name: dot-llama
  - mountPath: /.cache
    name: cache

nodeSelector: {}

tolerations: []

affinity: {}

secrets: {}
models:
  llama-3-2-3b-instruct:
    id: meta-llama/Llama-3.2-3B-Instruct
    enabled: false
  llama-guard-3-8b:
    id: meta-llama/Llama-Guard-3-8B
    enabled: false
    registerShield: true
  llama-3-2-1b-instruct:
    id: meta-llama/Llama-3.2-1B-Instruct
    enabled: false
  llama-3-1-8b-instruct:
    id: meta-llama/Llama-3.1-8B-Instruct
    enabled: false
  llama-guard-3-1b:
    id: meta-llama/Llama-Guard-3-1B
    enabled: false
    registerShield: true
  llama-3-3-70b-instruct:
    id: meta-llama/Llama-3.3-70B-Instruct
    enabled: false
  llama-3-2-1b-instruct-quantized:
    id: RedHatAI/Llama-3.2-1B-Instruct-quantized.w8a8
    enabled: false
